const { prisma } = require("./config/db");

const products = [
  {
    name: "Classic White Tee",
    description: "Essential cotton t-shirt",
    price: 9.99,
    stockQuantity: 100,
    imageUrl: "https://placehold.co/400x400?text=Tee",
  },
  {
    name: "Black Hoodie",
    description: "Warm pullover hoodie",
    price: 34.99,
    stockQuantity: 50,
    imageUrl: "https://placehold.co/400x400?text=Hoodie",
  },
  {
    name: "Slim Jeans",
    description: "Classic slim fit denim",
    price: 49.99,
    stockQuantity: 75,
    imageUrl: "https://placehold.co/400x400?text=Jeans",
  },
  {
    name: "Running Shoes",
    description: "Lightweight sport shoes",
    price: 89.99,
    stockQuantity: 40,
    imageUrl: "https://placehold.co/400x400?text=Shoes",
  },
  {
    name: "Leather Wallet",
    description: "Slim genuine leather wallet",
    price: 24.99,
    stockQuantity: 60,
    imageUrl: "https://placehold.co/400x400?text=Wallet",
  },
  {
    name: "Snapback Cap",
    description: "Adjustable flat brim cap",
    price: 19.99,
    stockQuantity: 80,
    imageUrl: "https://placehold.co/400x400?text=Cap",
  },
  {
    name: "Cargo Pants",
    description: "Multi-pocket cargo trousers",
    price: 44.99,
    stockQuantity: 35,
    imageUrl: "https://placehold.co/400x400?text=Cargo",
  },
  {
    name: "Bomber Jacket",
    description: "Classic bomber style jacket",
    price: 79.99,
    stockQuantity: 25,
    imageUrl: "https://placehold.co/400x400?text=Bomber",
  },
  {
    name: "Polo Shirt",
    description: "Pique cotton polo shirt",
    price: 29.99,
    stockQuantity: 90,
    imageUrl: "https://placehold.co/400x400?text=Polo",
  },
  {
    name: "Chino Pants",
    description: "Smart casual chino trousers",
    price: 39.99,
    stockQuantity: 55,
    imageUrl: "https://placehold.co/400x400?text=Chino",
  },
  {
    name: "Denim Jacket",
    description: "Classic denim jacket",
    price: 59.99,
    stockQuantity: 30,
    imageUrl: "https://placehold.co/400x400?text=Denim",
  },
  {
    name: "Graphic Tee",
    description: "Bold graphic print tee",
    price: 14.99,
    stockQuantity: 120,
    imageUrl: "https://placehold.co/400x400?text=Graphic",
  },
  {
    name: "Sweatpants",
    description: "Comfortable fleece sweatpants",
    price: 32.99,
    stockQuantity: 65,
    imageUrl: "https://placehold.co/400x400?text=Sweats",
  },
  {
    name: "Beanie Hat",
    description: "Knitted winter beanie",
    price: 12.99,
    stockQuantity: 95,
    imageUrl: "https://placehold.co/400x400?text=Beanie",
  },
  {
    name: "Oxford Shirt",
    description: "Button-down oxford shirt",
    price: 39.99,
    stockQuantity: 45,
    imageUrl: "https://placehold.co/400x400?text=Oxford",
  },
  {
    name: "Sneakers",
    description: "Classic low-top sneakers",
    price: 64.99,
    stockQuantity: 38,
    imageUrl: "https://placehold.co/400x400?text=Sneakers",
  },
  {
    name: "Windbreaker",
    description: "Lightweight wind jacket",
    price: 54.99,
    stockQuantity: 28,
    imageUrl: "https://placehold.co/400x400?text=Wind",
  },
  {
    name: "Tank Top",
    description: "Ribbed cotton tank top",
    price: 7.99,
    stockQuantity: 150,
    imageUrl: "https://placehold.co/400x400?text=Tank",
  },
  {
    name: "Shorts",
    description: "Casual cotton shorts",
    price: 22.99,
    stockQuantity: 85,
    imageUrl: "https://placehold.co/400x400?text=Shorts",
  },
  {
    name: "Trench Coat",
    description: "Classic belted trench coat",
    price: 119.99,
    stockQuantity: 15,
    imageUrl: "https://placehold.co/400x400?text=Trench",
  },
  {
    name: "Loafers",
    description: "Slip-on leather loafers",
    price: 74.99,
    stockQuantity: 32,
    imageUrl: "https://placehold.co/400x400?text=Loafers",
  },
  {
    name: "Bucket Hat",
    description: "Cotton bucket hat",
    price: 16.99,
    stockQuantity: 70,
    imageUrl: "https://placehold.co/400x400?text=Bucket",
  },
  {
    name: "Flannel Shirt",
    description: "Plaid flannel overshirt",
    price: 34.99,
    stockQuantity: 42,
    imageUrl: "https://placehold.co/400x400?text=Flannel",
  },
  {
    name: "Joggers",
    description: "Tapered jogger pants",
    price: 37.99,
    stockQuantity: 58,
    imageUrl: "https://placehold.co/400x400?text=Joggers",
  },
  {
    name: "Puffer Jacket",
    description: "Insulated puffer jacket",
    price: 99.99,
    stockQuantity: 20,
    imageUrl: "https://placehold.co/400x400?text=Puffer",
  },
  {
    name: "Turtleneck",
    description: "Ribbed turtleneck sweater",
    price: 42.99,
    stockQuantity: 48,
    imageUrl: "https://placehold.co/400x400?text=Turtle",
  },
  {
    name: "Linen Shirt",
    description: "Breathable linen summer shirt",
    price: 36.99,
    stockQuantity: 52,
    imageUrl: "https://placehold.co/400x400?text=Linen",
  },
  {
    name: "Chelsea Boots",
    description: "Elastic sided chelsea boots",
    price: 109.99,
    stockQuantity: 22,
    imageUrl: "https://placehold.co/400x400?text=Chelsea",
  },
  {
    name: "Corduroy Pants",
    description: "Retro corduroy trousers",
    price: 47.99,
    stockQuantity: 33,
    imageUrl: "https://placehold.co/400x400?text=Cord",
  },
  {
    name: "Zip Hoodie",
    description: "Full zip fleece hoodie",
    price: 44.99,
    stockQuantity: 44,
    imageUrl: "https://placehold.co/400x400?text=Zip",
  },
  {
    name: "Swim Shorts",
    description: "Quick-dry swim trunks",
    price: 27.99,
    stockQuantity: 66,
    imageUrl: "https://placehold.co/400x400?text=Swim",
  },
  {
    name: "Overshirt",
    description: "Heavyweight cotton overshirt",
    price: 52.99,
    stockQuantity: 29,
    imageUrl: "https://placehold.co/400x400?text=Over",
  },
  {
    name: "Slides",
    description: "Cushioned foam slides",
    price: 18.99,
    stockQuantity: 110,
    imageUrl: "https://placehold.co/400x400?text=Slides",
  },
  {
    name: "Knit Sweater",
    description: "Chunky knit crew sweater",
    price: 57.99,
    stockQuantity: 36,
    imageUrl: "https://placehold.co/400x400?text=Knit",
  },
  {
    name: "Track Jacket",
    description: "Retro track top jacket",
    price: 49.99,
    stockQuantity: 41,
    imageUrl: "https://placehold.co/400x400?text=Track",
  },
  {
    name: "Formal Trousers",
    description: "Tailored formal trousers",
    price: 62.99,
    stockQuantity: 27,
    imageUrl: "https://placehold.co/400x400?text=Formal",
  },
  {
    name: "Henley Shirt",
    description: "Button collar henley top",
    price: 23.99,
    stockQuantity: 77,
    imageUrl: "https://placehold.co/400x400?text=Henley",
  },
  {
    name: "High Tops",
    description: "Canvas high top sneakers",
    price: 54.99,
    stockQuantity: 43,
    imageUrl: "https://placehold.co/400x400?text=High",
  },
  {
    name: "Cardigan",
    description: "Open front knit cardigan",
    price: 47.99,
    stockQuantity: 39,
    imageUrl: "https://placehold.co/400x400?text=Cardi",
  },
  {
    name: "Leather Belt",
    description: "Classic pin buckle belt",
    price: 19.99,
    stockQuantity: 88,
    imageUrl: "https://placehold.co/400x400?text=Belt",
  },
  {
    name: "Compression Tee",
    description: "Stretch athletic base layer",
    price: 26.99,
    stockQuantity: 62,
    imageUrl: "https://placehold.co/400x400?text=Comp",
  },
  {
    name: "Parka",
    description: "Long hooded winter parka",
    price: 134.99,
    stockQuantity: 12,
    imageUrl: "https://placehold.co/400x400?text=Parka",
  },
  {
    name: "Dress Shirt",
    description: "Crisp white dress shirt",
    price: 44.99,
    stockQuantity: 46,
    imageUrl: "https://placehold.co/400x400?text=Dress",
  },
  {
    name: "Biker Jacket",
    description: "Faux leather moto jacket",
    price: 89.99,
    stockQuantity: 18,
    imageUrl: "https://placehold.co/400x400?text=Biker",
  },
  {
    name: "Socks Pack",
    description: "5-pack cotton ankle socks",
    price: 11.99,
    stockQuantity: 200,
    imageUrl: "https://placehold.co/400x400?text=Socks",
  },
  {
    name: "Muscle Tee",
    description: "Sleeveless cut-off tee",
    price: 8.99,
    stockQuantity: 130,
    imageUrl: "https://placehold.co/400x400?text=Muscle",
  },
  {
    name: "Utility Vest",
    description: "Multi-pocket utility vest",
    price: 38.99,
    stockQuantity: 24,
    imageUrl: "https://placehold.co/400x400?text=Vest",
  },
  {
    name: "Boat Shoes",
    description: "Classic leather boat shoes",
    price: 79.99,
    stockQuantity: 31,
    imageUrl: "https://placehold.co/400x400?text=Boat",
  },
  {
    name: "Thermal Tee",
    description: "Waffle knit thermal top",
    price: 21.99,
    stockQuantity: 73,
    imageUrl: "https://placehold.co/400x400?text=Thermal",
  },
  {
    name: "Coach Jacket",
    description: "Lightweight nylon coach jacket",
    price: 67.99,
    stockQuantity: 26,
    imageUrl: "https://placehold.co/400x400?text=Coach",
  },
];

const seed = async () => {
  await prisma.products.createMany({
    data: products,
  });
  console.log("Seeded!");
  await prisma.$disconnect();
};

seed();
